name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
   name: Deploy to Kubernetes
   runs-on: ubuntu-latest
   steps:
    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: GitHub Action Status - ${{ job.status }}
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
        content_type: text/plain
        body: |
          Hello,
    
          This is an automated notification of the status of your GitHub Actions workflow.
    
          Job Status: ${{ job.status }}
    
          - GitHub Actions

      
      
      
